import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { DecodoYouTubeExtractor } from "../index";

function createSubtitleResponse(options: {
  manual?: Record<string, { events: unknown[] }>;
  autoGenerated?: Record<string, { events: unknown[] }>;
}) {
  return {
    results: [
      {
        content: {
          ...(options.manual ? { manual: options.manual } : {}),
          ...(options.autoGenerated ? { auto_generated: options.autoGenerated } : {}),
        },
        status_code: 200,
        query: "dQw4w9WgXcQ",
      },
    ],
  };
}

function createMetadataResponse(options?: {
  title?: string;
  thumbnails?: Array<{ height: number; url: string; width: number }>;
}) {
  return {
    results: [
      {
        content: {
          parse_status_code: 12000,
          results: {
            title: options?.title ?? "Test Video Title",
            thumbnails: options?.thumbnails ?? [
              { height: 720, url: "https://i.ytimg.com/vi/test/maxresdefault.jpg", width: 1280 },
            ],
            duration: 300,
            upload_date: "20260101",
            uploader: "Test Channel",
            video_id: "dQw4w9WgXcQ",
          },
        },
        status_code: 200,
        query: "dQw4w9WgXcQ",
      },
    ],
  };
}

function makeEvents(texts: Array<{ text: string; startMs: number; durationMs: number }>) {
  return texts.map(({ text, startMs, durationMs }) => ({
    tStartMs: startMs,
    dDurationMs: durationMs,
    segs: text.split(" ").map((word, i) => ({
      utf8: i === 0 ? word : ` ${word}`,
      tOffsetMs: i * 100,
    })),
    wWinId: 1,
  }));
}

describe("DecodoYouTubeExtractor", () => {
  const extractor = new DecodoYouTubeExtractor({ authKey: "test-key" });
  let fetchSpy: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchSpy = vi.fn();
    vi.stubGlobal("fetch", fetchSpy);
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  function mockFetchResponses(subtitles: unknown, metadata: unknown) {
    fetchSpy
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(subtitles),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(metadata),
      });
  }

  it("extracts transcript and metadata from a valid video", async () => {
    const events = makeEvents([
      { text: "Hello world", startMs: 0, durationMs: 3000 },
      { text: "Second segment", startMs: 3000, durationMs: 2000 },
    ]);

    mockFetchResponses(
      createSubtitleResponse({ autoGenerated: { en: { events } } }),
      createMetadataResponse(),
    );

    const result = await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");

    expect(result.title).toBe("Test Video Title");
    expect(result.metadata?.provider).toBe("decodo");
    expect(result.metadata?.videoId).toBe("dQw4w9WgXcQ");
    expect(result.metadata?.thumbnailUrl).toBe("https://i.ytimg.com/vi/test/maxresdefault.jpg");
    expect(result.markdown).toContain("# Test Video Title");
    expect(result.markdown).toContain("Hello world");
    expect(result.markdown).toContain("Second segment");
  });

  it("prefers manual subtitles over auto-generated", async () => {
    const manualEvents = makeEvents([{ text: "Manual caption", startMs: 0, durationMs: 3000 }]);
    const autoEvents = makeEvents([{ text: "Auto caption", startMs: 0, durationMs: 3000 }]);

    mockFetchResponses(
      createSubtitleResponse({
        manual: { en: { events: manualEvents } },
        autoGenerated: { en: { events: autoEvents } },
      }),
      createMetadataResponse(),
    );

    const result = await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.markdown).toContain("Manual caption");
    expect(result.markdown).not.toContain("Auto caption");
  });

  it("filters out aAppend events (newline continuations)", async () => {
    const events = [
      ...makeEvents([{ text: "Real segment", startMs: 0, durationMs: 3000 }]),
      { tStartMs: 1500, dDurationMs: 500, segs: [{ utf8: "\n" }], aAppend: 1, wWinId: 1 },
    ];

    mockFetchResponses(
      createSubtitleResponse({ autoGenerated: { en: { events } } }),
      createMetadataResponse(),
    );

    const result = await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.markdown).toContain("Real segment");
    // The aAppend newline event should not produce its own text segment
    const lines = result.markdown
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
    const textLines = lines.filter((l) => !l.startsWith("#"));
    expect(textLines).toEqual(["Real segment"]);
  });

  it("inserts timestamp headers every 60 seconds", async () => {
    const events = makeEvents([
      { text: "Start of video", startMs: 0, durationMs: 3000 },
      { text: "One minute in", startMs: 60000, durationMs: 3000 },
      { text: "Two minutes in", startMs: 120000, durationMs: 3000 },
    ]);

    mockFetchResponses(
      createSubtitleResponse({ autoGenerated: { en: { events } } }),
      createMetadataResponse(),
    );

    const result = await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.markdown).toContain("## [0:00]");
    expect(result.markdown).toContain("## [1:00]");
    expect(result.markdown).toContain("## [2:00]");
  });

  it("picks the highest-resolution thumbnail", async () => {
    const events = makeEvents([{ text: "Some text", startMs: 0, durationMs: 3000 }]);

    mockFetchResponses(
      createSubtitleResponse({ autoGenerated: { en: { events } } }),
      createMetadataResponse({
        thumbnails: [
          { height: 94, url: "https://i.ytimg.com/small.jpg", width: 168 },
          { height: 1080, url: "https://i.ytimg.com/fullhd.jpg", width: 1920 },
          { height: 720, url: "https://i.ytimg.com/hd.jpg", width: 1280 },
        ],
      }),
    );

    const result = await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.metadata?.thumbnailUrl).toBe("https://i.ytimg.com/fullhd.jpg");
  });

  it("returns undefined thumbnailUrl when no thumbnails available", async () => {
    const events = makeEvents([{ text: "Some text", startMs: 0, durationMs: 3000 }]);

    mockFetchResponses(
      createSubtitleResponse({ autoGenerated: { en: { events } } }),
      createMetadataResponse({ thumbnails: [] }),
    );

    const result = await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.metadata?.thumbnailUrl).toBeUndefined();
  });

  it("throws when no transcript segments found", async () => {
    mockFetchResponses(createSubtitleResponse({}), createMetadataResponse());

    await expect(extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ")).rejects.toThrow(
      "No transcript segments found",
    );
  });

  it("throws when video ID cannot be extracted", async () => {
    await expect(extractor.extract("https://example.com/not-youtube")).rejects.toThrow(
      "Could not extract video ID",
    );
  });

  it("throws on non-200 HTTP response", async () => {
    fetchSpy
      .mockResolvedValueOnce({
        ok: false,
        status: 429,
        text: () => Promise.resolve("Rate limited"),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(createMetadataResponse()),
      });

    await expect(extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ")).rejects.toThrow(
      "Decodo API error (429): Rate limited",
    );
  });

  it("throws on per-result non-200 status code", async () => {
    fetchSpy
      .mockResolvedValueOnce({
        ok: true,
        json: () =>
          Promise.resolve({
            results: [{ content: {}, status_code: 404, query: "dQw4w9WgXcQ" }],
          }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(createMetadataResponse()),
      });

    await expect(extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ")).rejects.toThrow(
      'Decodo scrape failed for youtube_subtitles query "dQw4w9WgXcQ" with status 404',
    );
  });

  it("throws when Decodo returns empty results array", async () => {
    fetchSpy
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ results: [] }),
      })
      .mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(createMetadataResponse()),
      });

    await expect(extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ")).rejects.toThrow(
      "Decodo returned no results",
    );
  });

  it("sends correct request headers and body", async () => {
    const events = makeEvents([{ text: "Hello", startMs: 0, durationMs: 1000 }]);

    mockFetchResponses(
      createSubtitleResponse({ autoGenerated: { en: { events } } }),
      createMetadataResponse(),
    );

    await extractor.extract("https://youtube.com/watch?v=dQw4w9WgXcQ");

    expect(fetchSpy).toHaveBeenCalledTimes(2);

    const [subtitleCall, metadataCall] = fetchSpy.mock.calls;
    expect(subtitleCall[1].headers.Authorization).toBe("Basic test-key");
    expect(JSON.parse(subtitleCall[1].body)).toEqual({
      target: "youtube_subtitles",
      query: "dQw4w9WgXcQ",
    });
    expect(JSON.parse(metadataCall[1].body)).toEqual({
      target: "youtube_metadata",
      query: "dQw4w9WgXcQ",
    });
  });
});
