/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SigninRouteImport } from "./routes/signin";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiE2eSeedRouteImport } from "./routes/api/e2e-seed";
import { Route as ApiE2eResetRouteImport } from "./routes/api/e2e-reset";
import { Route as ApiE2eCleanupRouteImport } from "./routes/api/e2e-cleanup";
import { Route as AuthenticatedUploadRouteImport } from "./routes/_authenticated/upload";
import { Route as AuthenticatedSavedRouteImport } from "./routes/_authenticated/saved";
import { Route as AuthenticatedFeedRouteImport } from "./routes/_authenticated/feed";
import { Route as AuthenticatedLibraryIndexRouteImport } from "./routes/_authenticated/library/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as AuthenticatedLibraryDocumentIdRouteImport } from "./routes/_authenticated/library/$documentId";

const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiE2eSeedRoute = ApiE2eSeedRouteImport.update({
  id: "/api/e2e-seed",
  path: "/api/e2e-seed",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiE2eResetRoute = ApiE2eResetRouteImport.update({
  id: "/api/e2e-reset",
  path: "/api/e2e-reset",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiE2eCleanupRoute = ApiE2eCleanupRouteImport.update({
  id: "/api/e2e-cleanup",
  path: "/api/e2e-cleanup",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: "/upload",
  path: "/upload",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedLibraryIndexRoute = AuthenticatedLibraryIndexRouteImport.update({
  id: "/library/",
  path: "/library/",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedLibraryDocumentIdRoute = AuthenticatedLibraryDocumentIdRouteImport.update({
  id: "/library/$documentId",
  path: "/library/$documentId",
  getParentRoute: () => AuthenticatedRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/signin": typeof SigninRoute;
  "/feed": typeof AuthenticatedFeedRoute;
  "/saved": typeof AuthenticatedSavedRoute;
  "/upload": typeof AuthenticatedUploadRoute;
  "/api/e2e-cleanup": typeof ApiE2eCleanupRoute;
  "/api/e2e-reset": typeof ApiE2eResetRoute;
  "/api/e2e-seed": typeof ApiE2eSeedRoute;
  "/library/$documentId": typeof AuthenticatedLibraryDocumentIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/library/": typeof AuthenticatedLibraryIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/signin": typeof SigninRoute;
  "/feed": typeof AuthenticatedFeedRoute;
  "/saved": typeof AuthenticatedSavedRoute;
  "/upload": typeof AuthenticatedUploadRoute;
  "/api/e2e-cleanup": typeof ApiE2eCleanupRoute;
  "/api/e2e-reset": typeof ApiE2eResetRoute;
  "/api/e2e-seed": typeof ApiE2eSeedRoute;
  "/library/$documentId": typeof AuthenticatedLibraryDocumentIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/library": typeof AuthenticatedLibraryIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/_authenticated/feed": typeof AuthenticatedFeedRoute;
  "/_authenticated/saved": typeof AuthenticatedSavedRoute;
  "/_authenticated/upload": typeof AuthenticatedUploadRoute;
  "/api/e2e-cleanup": typeof ApiE2eCleanupRoute;
  "/api/e2e-reset": typeof ApiE2eResetRoute;
  "/api/e2e-seed": typeof ApiE2eSeedRoute;
  "/_authenticated/library/$documentId": typeof AuthenticatedLibraryDocumentIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/_authenticated/library/": typeof AuthenticatedLibraryIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/signin"
    | "/feed"
    | "/saved"
    | "/upload"
    | "/api/e2e-cleanup"
    | "/api/e2e-reset"
    | "/api/e2e-seed"
    | "/library/$documentId"
    | "/api/auth/$"
    | "/library/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/signin"
    | "/feed"
    | "/saved"
    | "/upload"
    | "/api/e2e-cleanup"
    | "/api/e2e-reset"
    | "/api/e2e-seed"
    | "/library/$documentId"
    | "/api/auth/$"
    | "/library";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/signin"
    | "/_authenticated/feed"
    | "/_authenticated/saved"
    | "/_authenticated/upload"
    | "/api/e2e-cleanup"
    | "/api/e2e-reset"
    | "/api/e2e-seed"
    | "/_authenticated/library/$documentId"
    | "/api/auth/$"
    | "/_authenticated/library/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  SigninRoute: typeof SigninRoute;
  ApiE2eCleanupRoute: typeof ApiE2eCleanupRoute;
  ApiE2eResetRoute: typeof ApiE2eResetRoute;
  ApiE2eSeedRoute: typeof ApiE2eSeedRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/e2e-seed": {
      id: "/api/e2e-seed";
      path: "/api/e2e-seed";
      fullPath: "/api/e2e-seed";
      preLoaderRoute: typeof ApiE2eSeedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/e2e-reset": {
      id: "/api/e2e-reset";
      path: "/api/e2e-reset";
      fullPath: "/api/e2e-reset";
      preLoaderRoute: typeof ApiE2eResetRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/e2e-cleanup": {
      id: "/api/e2e-cleanup";
      path: "/api/e2e-cleanup";
      fullPath: "/api/e2e-cleanup";
      preLoaderRoute: typeof ApiE2eCleanupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/upload": {
      id: "/_authenticated/upload";
      path: "/upload";
      fullPath: "/upload";
      preLoaderRoute: typeof AuthenticatedUploadRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/saved": {
      id: "/_authenticated/saved";
      path: "/saved";
      fullPath: "/saved";
      preLoaderRoute: typeof AuthenticatedSavedRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/feed": {
      id: "/_authenticated/feed";
      path: "/feed";
      fullPath: "/feed";
      preLoaderRoute: typeof AuthenticatedFeedRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/library/": {
      id: "/_authenticated/library/";
      path: "/library";
      fullPath: "/library/";
      preLoaderRoute: typeof AuthenticatedLibraryIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/library/$documentId": {
      id: "/_authenticated/library/$documentId";
      path: "/library/$documentId";
      fullPath: "/library/$documentId";
      preLoaderRoute: typeof AuthenticatedLibraryDocumentIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute;
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute;
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute;
  AuthenticatedLibraryDocumentIdRoute: typeof AuthenticatedLibraryDocumentIdRoute;
  AuthenticatedLibraryIndexRoute: typeof AuthenticatedLibraryIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedLibraryDocumentIdRoute: AuthenticatedLibraryDocumentIdRoute,
  AuthenticatedLibraryIndexRoute: AuthenticatedLibraryIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  ApiE2eCleanupRoute: ApiE2eCleanupRoute,
  ApiE2eResetRoute: ApiE2eResetRoute,
  ApiE2eSeedRoute: ApiE2eSeedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
