/**
 * Caption tracks extraction with player API and Android player fallback.
 *
 * Ported from @steipete/summarize-core by Peter Steinberger.
 * Original: https://github.com/steipete/summarize/blob/main/packages/core/src/content/transcript/providers/youtube/captions-transcript.ts
 * License: MIT — https://github.com/steipete/summarize/blob/main/LICENSE
 */

import { extractYoutubeiBootstrap } from "./api";
import {
  type TranscriptSegment,
  decodeHtmlEntities,
  extractBalancedJsonObject,
  fetchWithTimeout,
  isRecord,
  parseTimestampToMs,
  sanitizeYoutubeJsonResponse,
} from "./utils";

export interface TranscriptPayload {
  text: string;
  segments: TranscriptSegment[] | null;
}

const REQUEST_HEADERS: Record<string, string> = {
  "User-Agent":
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
  "Accept-Language": "en-US,en;q=0.9",
};

const YT_INITIAL_PLAYER_RESPONSE_TOKEN = "ytInitialPlayerResponse";
const INNERTUBE_API_KEY_REGEX =
  /"INNERTUBE_API_KEY":"([^"]+)"|INNERTUBE_API_KEY\\":\\"([^\\"]+)\\"/;

function extractInitialPlayerResponse(html: string): Record<string, unknown> | null {
  const tokenIndex = html.indexOf(YT_INITIAL_PLAYER_RESPONSE_TOKEN);
  if (tokenIndex < 0) return null;
  const assignmentIndex = html.indexOf("=", tokenIndex);
  if (assignmentIndex < 0) return null;
  const objectText = extractBalancedJsonObject(html, assignmentIndex);
  if (!objectText) return null;

  try {
    const parsed: unknown = JSON.parse(objectText);
    return isRecord(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function extractInnertubeApiKey(html: string): string | null {
  const match = html.match(INNERTUBE_API_KEY_REGEX);
  const key = match?.[1] ?? match?.[2] ?? null;
  return typeof key === "string" && key.trim().length > 0 ? key.trim() : null;
}

async function fetchTranscriptViaAndroidPlayer(args: {
  html: string;
  videoId: string;
  skipAutoGenerated?: boolean;
}): Promise<TranscriptPayload | null> {
  const apiKey = extractInnertubeApiKey(args.html);
  if (!apiKey) return null;

  try {
    const response = await fetchWithTimeout(
      `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "User-Agent": REQUEST_HEADERS["User-Agent"]!,
          "Accept-Language": REQUEST_HEADERS["Accept-Language"]!,
          Accept: "application/json",
        },
        body: JSON.stringify({
          context: { client: { clientName: "ANDROID", clientVersion: "20.10.38" } },
          videoId: args.videoId,
        }),
      },
    );

    if (!response.ok) return null;
    const parsed: unknown = await response.json();
    if (!isRecord(parsed)) return null;
    return extractTranscriptFromPlayerPayload(parsed, args.skipAutoGenerated);
  } catch {
    return null;
  }
}

export async function fetchTranscriptFromCaptionTracks(args: {
  html: string;
  originalUrl: string;
  videoId: string;
  skipAutoGenerated?: boolean;
}): Promise<TranscriptPayload | null> {
  const { html, originalUrl, videoId, skipAutoGenerated } = args;

  // Try extracting from initial player response embedded in page HTML
  const initialPlayerResponse = extractInitialPlayerResponse(html);
  if (initialPlayerResponse) {
    const transcript = await extractTranscriptFromPlayerPayload(
      initialPlayerResponse,
      skipAutoGenerated,
    );
    if (transcript) return transcript;
  }

  // Try via bootstrapped player API
  const bootstrap = extractYoutubeiBootstrap(html);
  if (!bootstrap) {
    return fetchTranscriptViaAndroidPlayer({ html, videoId, skipAutoGenerated });
  }

  const { apiKey, clientName, clientVersion, context, pageCl, pageLabel, visitorData, xsrfToken } =
    bootstrap;
  if (!apiKey) {
    return fetchTranscriptViaAndroidPlayer({ html, videoId, skipAutoGenerated });
  }

  const contextRecord = context as Record<string, unknown> & { client?: unknown };
  const clientContext = isRecord(contextRecord.client)
    ? (contextRecord.client as Record<string, unknown>)
    : {};

  const requestBody: Record<string, unknown> = {
    context: {
      ...contextRecord,
      client: { ...clientContext, originalUrl },
    },
    videoId,
    playbackContext: { contentPlaybackContext: { html5Preference: "HTML5_PREF_WANTS" } },
    contentCheckOk: true,
    racyCheckOk: true,
  };

  try {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      "User-Agent": REQUEST_HEADERS["User-Agent"]!,
      Accept: "application/json",
      Origin: "https://www.youtube.com",
      Referer: originalUrl,
      "X-Goog-AuthUser": "0",
      "X-Youtube-Bootstrap-Logged-In": "false",
    };

    if (clientName) headers["X-Youtube-Client-Name"] = clientName;
    if (clientVersion) headers["X-Youtube-Client-Version"] = clientVersion;
    if (visitorData) headers["X-Goog-Visitor-Id"] = visitorData;
    if (typeof pageCl === "number" && Number.isFinite(pageCl)) {
      headers["X-Youtube-Page-CL"] = String(pageCl);
    }
    if (pageLabel) headers["X-Youtube-Page-Label"] = pageLabel;
    if (xsrfToken) headers["X-Youtube-Identity-Token"] = xsrfToken;

    const response = await fetchWithTimeout(
      `https://www.youtube.com/youtubei/v1/player?key=${apiKey}`,
      { method: "POST", headers, body: JSON.stringify(requestBody) },
    );

    if (!response.ok) {
      return fetchTranscriptViaAndroidPlayer({ html, videoId, skipAutoGenerated });
    }

    const raw = await response.text();
    const sanitized = sanitizeYoutubeJsonResponse(raw);
    const parsed: unknown = JSON.parse(sanitized);
    if (!isRecord(parsed)) {
      return fetchTranscriptViaAndroidPlayer({ html, videoId, skipAutoGenerated });
    }

    const transcript = await extractTranscriptFromPlayerPayload(parsed, skipAutoGenerated);
    if (transcript) return transcript;

    return fetchTranscriptViaAndroidPlayer({ html, videoId, skipAutoGenerated });
  } catch {
    return fetchTranscriptViaAndroidPlayer({ html, videoId, skipAutoGenerated });
  }
}

type CaptionTrackRecord = Record<string, unknown> & {
  languageCode?: unknown;
  kind?: unknown;
  baseUrl?: unknown;
  url?: unknown;
};

async function extractTranscriptFromPlayerPayload(
  payload: Record<string, unknown>,
  skipAutoGenerated?: boolean,
): Promise<TranscriptPayload | null> {
  const captionsCandidate = payload.captions;
  const captions = isRecord(captionsCandidate) ? captionsCandidate : null;

  const rendererCandidate =
    (captions ? (captions as Record<string, unknown>).playerCaptionsTracklistRenderer : null) ??
    payload.playerCaptionsTracklistRenderer;

  const renderer = isRecord(rendererCandidate) ? rendererCandidate : null;
  const captionTracks = Array.isArray(renderer?.captionTracks)
    ? (renderer?.captionTracks as unknown[])
    : null;
  const automaticTracks = Array.isArray(renderer?.automaticCaptions)
    ? (renderer?.automaticCaptions as unknown[])
    : null;

  const orderedTracks: Record<string, unknown>[] = [];
  if (captionTracks) {
    orderedTracks.push(
      ...captionTracks.filter((track): track is Record<string, unknown> => isRecord(track)),
    );
  }
  if (!skipAutoGenerated && automaticTracks) {
    orderedTracks.push(
      ...automaticTracks.filter((track): track is Record<string, unknown> => isRecord(track)),
    );
  }

  const sortedTracks = [...orderedTracks].sort(
    (a: Record<string, unknown>, b: Record<string, unknown>) => {
      const aKind =
        typeof (a as CaptionTrackRecord).kind === "string"
          ? ((a as CaptionTrackRecord).kind as string)
          : "";
      const bKind =
        typeof (b as CaptionTrackRecord).kind === "string"
          ? ((b as CaptionTrackRecord).kind as string)
          : "";
      if (aKind === "asr" && bKind !== "asr") return 1;
      if (bKind === "asr" && aKind !== "asr") return -1;
      const aLang =
        typeof (a as CaptionTrackRecord).languageCode === "string"
          ? ((a as CaptionTrackRecord).languageCode as string)
          : "";
      const bLang =
        typeof (b as CaptionTrackRecord).languageCode === "string"
          ? ((b as CaptionTrackRecord).languageCode as string)
          : "";
      const aIsEnglish = aLang === "en" || aLang.startsWith("en-");
      const bIsEnglish = bLang === "en" || bLang.startsWith("en-");
      if (aIsEnglish && !bIsEnglish) return -1;
      if (bIsEnglish && !aIsEnglish) return 1;
      return 0;
    },
  );

  // Deduplicate by language
  const seenLanguages = new Set<string>();
  const normalizedTracks: Record<string, unknown>[] = [];
  for (const candidate of sortedTracks) {
    const lang =
      typeof (candidate as CaptionTrackRecord).languageCode === "string"
        ? ((candidate as CaptionTrackRecord).languageCode as string).toLowerCase()
        : "";
    if (lang && seenLanguages.has(lang)) continue;
    if (lang) seenLanguages.add(lang);
    normalizedTracks.push(candidate);
  }

  const tracksToUse = skipAutoGenerated
    ? normalizedTracks.filter((track) => (track as CaptionTrackRecord).kind !== "asr")
    : normalizedTracks;

  if (tracksToUse.length === 0) return null;
  return findFirstTranscript(tracksToUse, 0);
}

async function findFirstTranscript(
  tracks: readonly Record<string, unknown>[],
  index: number,
): Promise<TranscriptPayload | null> {
  if (index >= tracks.length) return null;
  const candidate = await downloadCaptionTrack(tracks[index] ?? {});
  if (candidate) return candidate;
  return findFirstTranscript(tracks, index + 1);
}

async function downloadCaptionTrack(
  track: Record<string, unknown>,
): Promise<TranscriptPayload | null> {
  const trackRecord = track as CaptionTrackRecord;
  const baseUrl =
    typeof trackRecord.baseUrl === "string"
      ? trackRecord.baseUrl
      : typeof trackRecord.url === "string"
        ? trackRecord.url
        : null;
  if (!baseUrl) return null;

  const json3Url = (() => {
    try {
      const parsed = new URL(baseUrl);
      parsed.searchParams.set("fmt", "json3");
      parsed.searchParams.set("alt", "json");
      return parsed.toString();
    } catch {
      const separator = baseUrl.includes("?") ? "&" : "?";
      return `${baseUrl}${separator}fmt=json3&alt=json`;
    }
  })();

  try {
    const response = await fetchWithTimeout(json3Url, { headers: REQUEST_HEADERS });
    if (!response.ok) return downloadXmlTranscript(baseUrl);

    const text = await response.text();
    if (text.length === 0) return downloadXmlTranscript(baseUrl);
    const jsonResult = parseJsonTranscript(text);
    if (jsonResult) return jsonResult;
    const xmlFallback = parseXmlTranscript(text);
    if (xmlFallback) return xmlFallback;
    return downloadXmlTranscript(baseUrl);
  } catch {
    return downloadXmlTranscript(baseUrl);
  }
}

async function downloadXmlTranscript(baseUrl: string): Promise<TranscriptPayload | null> {
  const xmlUrl = baseUrl.replaceAll(/&fmt=[^&]+/g, "");
  try {
    const response = await fetchWithTimeout(xmlUrl, { headers: REQUEST_HEADERS });
    if (!response.ok) return null;
    const text = await response.text();
    return parseJsonTranscript(text) ?? parseXmlTranscript(text);
  } catch {
    return null;
  }
}

type CaptionEventRecord = Record<string, unknown> & {
  segs?: unknown;
  tStartMs?: unknown;
  dDurationMs?: unknown;
};
type CaptionSegmentRecord = Record<string, unknown> & { utf8?: unknown };

function parseJsonTranscript(raw: string): TranscriptPayload | null {
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) return null;
    const events = (parsed as { events?: unknown }).events;
    if (!Array.isArray(events)) return null;

    const lines: string[] = [];
    const segments: TranscriptSegment[] = [];

    for (const event of events) {
      if (!isRecord(event)) continue;
      const eventRecord = event as CaptionEventRecord;
      const segs = Array.isArray(eventRecord.segs) ? (eventRecord.segs as unknown[]) : null;
      if (!segs) continue;

      const text = segs
        .map((seg) => {
          if (!isRecord(seg)) return "";
          return typeof (seg as CaptionSegmentRecord).utf8 === "string"
            ? ((seg as CaptionSegmentRecord).utf8 as string)
            : "";
        })
        .join("")
        .trim();

      if (text.length > 0) {
        lines.push(text);
        const startMs = parseTimestampToMs(eventRecord.tStartMs, false);
        const durationMs = parseTimestampToMs(eventRecord.dDurationMs, false);
        if (startMs != null) {
          segments.push({
            startMs,
            endMs: durationMs != null ? startMs + durationMs : null,
            text: text.replace(/\s+/g, " ").trim(),
          });
        }
      }
    }

    const transcript = lines.join("\n").trim();
    if (transcript.length === 0) return null;
    return { text: transcript, segments: segments.length > 0 ? segments : null };
  } catch {
    return null;
  }
}

function parseXmlTranscript(xml: string): TranscriptPayload | null {
  const pattern = /<text[^>]*>([\s\S]*?)<\/text>/gi;
  const lines: string[] = [];
  const segments: TranscriptSegment[] = [];
  let match: RegExpExecArray | null = pattern.exec(xml);

  while (match) {
    const content = match[1] ?? "";
    const decoded = decodeHtmlEntities(content).replaceAll(/\s+/g, " ").trim();
    if (decoded.length > 0) {
      lines.push(decoded);
      const tag = match[0] ?? "";
      const startMatch = tag.match(/\bstart\s*=\s*(['"])([^'"]+)\1/i);
      const durMatch = tag.match(/\bdur\s*=\s*(['"])([^'"]+)\1/i);
      const startMs = startMatch?.[2] ? parseTimestampToMs(startMatch[2], true) : null;
      const durationMs = durMatch?.[2] ? parseTimestampToMs(durMatch[2], true) : null;
      if (startMs != null) {
        segments.push({
          startMs,
          endMs: durationMs != null ? startMs + durationMs : null,
          text: decoded.replace(/\s+/g, " ").trim(),
        });
      }
    }
    match = pattern.exec(xml);
  }

  const transcript = lines.join("\n").trim();
  if (transcript.length === 0) return null;
  return { text: transcript, segments: segments.length > 0 ? segments : null };
}
